### ISSUE TITLE
Is that possible to define 'half day'?

### ISSUE THREAD

**Issue by tcagkansokmen** [code16/carbon-business-days#4]
Etc. There's an holiday just from 09.00 to 13.00 and it let me to make HALF DAY Closed.
And I want to calculate it as a 0.5 days.

How can this be possible?

**Comment by dvlpp** [comment]
Not a the moment, sorry for that. I'm not sure it would be easy to implement because half day can be hard to define. I think I would go for an hour based calculation for this.
